name: Deploy Rust docs to GitHub Pages

on:
  push:
    branches: main
  workflow_dispatch:

env:
  MDBOOK_VERSION: "0.4.52"
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup Rust
      run: rustup update stable --no-self-update && rustup default stable
    - name: Build book
      run: |
        mkdir -p /tmp/mdbook
        curl -Lo- https://github.com/rust-lang/mdBook/releases/download/v${{ env.MDBOOK_VERSION }}/mdbook-v${{ env.MDBOOK_VERSION }}-x86_64-unknown-linux-gnu.tar.gz | tar -C /tmp/mdbook -xzv
        /tmp/mdbook/mdbook build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./book

  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
